# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0002_auto_20161026_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisation',
            field=models.NullBooleanField(),
        ),
    ]
