# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0002_auto_20180128_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='login',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
