# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0003_auto_20180129_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisations_en_lien',
            field=models.ManyToManyField(blank=True, null=True, to='revendication.Organisation'),
        ),
    ]
