# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0004_auto_20180130_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisations_en_lien',
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation',
            field=models.ManyToManyField(null=True, related_name='_organisation_organisation_+', to='revendication.Organisation'),
        ),
    ]
