# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revendication', '0005_militant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('lieu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Lieu')),
            ],
        ),
        migrations.AlterField(
            model_name='soutien',
            name='propositions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Proposition'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(null=True, through='revendication.Soutien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenement',
            name='proposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Proposition'),
        ),
        migrations.AddField(
            model_name='soutien',
            name='evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Evenement'),
        ),
    ]
