# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0005_auto_20180130_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisation',
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_en_lien',
            field=models.ManyToManyField(null=True, related_name='_organisation_organisation_en_lien_+', to='revendication.Organisation'),
        ),
    ]
