# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revendication', '0006_auto_20161218_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militant',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='militant',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='organisation',
            name='adherent',
            field=models.ManyToManyField(null=True, through='revendication.Soutien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soutien',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Organisation'),
        ),
        migrations.DeleteModel(
            name='Militant',
        ),
    ]
