# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0007_auto_20161218_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Titre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
