# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0007_auto_20180130_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='organisation_en_lien',
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_en_lien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Organisation'),
        ),
    ]
