# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0008_auto_20180130_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_en_lien',
            new_name='organisations_en_lien',
        ),
    ]
