# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0009_auto_20161226_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutien',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date création soutien'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='objectif_de_signataires',
            field=models.IntegerField(null=True),
        ),
    ]
