# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0010_auto_20170226_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='titre',
        ),
    ]
