# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revendication', '0010_auto_20180130_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='soutien',
            name='organisation',
        ),
        migrations.AddField(
            model_name='organisation',
            name='soutiens',
            field=models.ManyToManyField(blank=True, null=True, to='revendication.Soutien'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
