# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0011_remove_evenement_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
