# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0013_auto_20180202_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='organisations_en_lien',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='petition',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='proposition',
        ),
    ]
