# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0014_auto_20170430_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='lieu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
