# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0017_auto_20170430_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='categorie',
        ),
        migrations.AddField(
            model_name='proposition',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
