# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0018_auto_20170710_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutien',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Competence'),
        ),
        migrations.AlterField(
            model_name='soutien',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Evenement'),
        ),
        migrations.AlterField(
            model_name='soutien',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Organisation'),
        ),
        migrations.AlterField(
            model_name='soutien',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Petition'),
        ),
    ]
