# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0019_auto_20171116_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('texte', 'texte'), ('article', 'article'), ('image', 'image'), ('video', 'video'), ('autre', 'autre')], max_length=10)),
                ('date_creation', models.DateField(auto_now=True, verbose_name='Date création document')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Competence')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Evenement')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Organisation')),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Petition')),
                ('proposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Proposition')),
            ],
        ),
    ]
