# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revendication', '0020_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='personnes',
            field=models.ManyToManyField(null=True, through='revendication.Soutien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soutien',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revendication.Document'),
        ),
    ]
