# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0021_auto_20171218_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='upload',
            new_name='fichier',
        ),
    ]
