# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revendication', '0022_auto_20171218_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
